FROM        node:8

WORKDIR     /usr/src/app

COPY        package*.json ./

RUN         npm install

COPY        . .

EXPOSE      49160:8080


RUN         echo 'alias ll="ls -l"' >> ~/.bashrc

ENTRYPOINT  npm run dev
#CMD         ["npm", "run dev"]
