FROM debian:latest

WORKDIR /encoder

COPY . /encoder

RUN ls
RUN apt-get update && \
    apt-get install -y ffmpeg && \
    apt-get install -y python3 && \
    apt-get install -y python3-pip && \
    pip3 install --upgrade pip && \
    pip install -r requirements.txt

RUN echo 'alias ll="ls -l"' >> ~/.bashrc && \
    echo 'alias py="python3"' >> ~/.bashrc

CMD ["python3", "server.py"]